Adding spatial mating functions
HighlanderLab/SIMplyBee pull request #505
Opened 2023-03-09 16:27 UTC by janaobsteter

Added:
- `createSpatialMatingPlan`
- changed `cross` functions to allow for taking drone producing colonies (not drones directly) --> created three alias cross functions: `crossDronePackages`, `crossDroneID`, `crossColonyID` (with the option to sample or create drones)

2023-03-09 16:28 UTC, janaobsteter commented
This is intermediate step!!! Once this works, I will incorporate the spatial into the cross function.

2023-03-09 23:03 UTC, gregorgorjanc commented
@janaobsteter the above states there are merge conflicts in this PR - is this due to the mine rcircle PR? Can you resolve this before I review?

2023-03-13 14:57 UTC, janaobsteter commented
@gregorgorjanc , conflict resolved (we did throw the location out of createColony(), right?

2023-05-23 12:46 UTC, gregorgorjanc commented on DESCRIPTION
> +Depends: R (>= 3.3.0), AlphaSimR (>= 1.3.2), RANN, ggplot2
I think RANN needs to go to imports and lets see how to use base R plotting to have less dependencies

2023-05-23 12:46 UTC, gregorgorjanc commented on NEWS.md
>  * TODO
@janaobsteter add a line re new functionality

2023-05-23 12:48 UTC, gregorgorjanc commented on R/Functions_L0_auxilary.R
> +#' @title Create a cross plan by sampling drone producing
"by sampling drones or drone producing colonies"

2023-05-23 12:50 UTC, gregorgorjanc commented on R/Functions_L0_auxilary.R
> +#'   congregation ares) available for mating. When \code{spatial = TRUE}, the user can not
area

2023-05-23 12:53 UTC, gregorgorjanc commented on R/Functions_L0_auxilary.R
> +#' @return named list with names being virgin input IDs with each
Sync

2023-05-23 12:58 UTC, gregorgorjanc commented on R/Functions_L0_auxilary.R
> +#' ggplot(data = locations1, aes(x = V1, y = V2, shape = Type )) +
As above

2023-05-23 13:02 UTC, gregorgorjanc commented on R/Functions_L0_auxilary.R
> +    droneColonyId <- getId(droneColonies)
Remove this line?

2023-05-23 13:05 UTC, gregorgorjanc commented on R/Functions_L1_Pop.R
> +#'   stored for producing progeny at a later stage. Since this is a complex
Remove this part since now the function is not that complex (well not as much as you thought)

2023-05-23 13:12 UTC, gregorgorjanc commented on R/Functions_L1_Pop.R
>                    checkMating = "error",
Should this be named differently? `checkCross`?

2023-05-23 13:14 UTC, gregorgorjanc commented on R/Functions_L1_Pop.R
> +    nD <- nDrones(x = x, ...)
Maybe this does not work since you don't have it in the function definition?

2023-05-23 13:16 UTC, gregorgorjanc commented on R/Functions_L1_Pop.R
> +      message("There are no matches for some colonies! The cross() will fail
"matches" --> "... there are not potential crosses ..."

2023-05-23 13:16 UTC, gregorgorjanc commented on R/Functions_L1_Pop.R
> +              unless argument checkMating is set to 'warning'.")
`checkCross`

2023-05-23 13:17 UTC, gregorgorjanc commented on R/Functions_L1_Pop.R
> +            nSelected <- table(sample(virginMatches, size = nDrones, replace = TRUE))
nSelected to selected

2023-05-23 13:33 UTC, gregorgorjanc requested changes
Minor points

would be good to get later feedback from @LStrachan and @JerBub once this is in the package - also Irene

2023-05-23 13:33 UTC, gregorgorjanc commented on R/Functions_L1_Pop.R
>          msg <- "Mating failed!"
Crossing

2023-05-23 13:33 UTC, gregorgorjanc commented on vignettes/D_Crossing.Rmd
> +and at the end we describe two special cases of mating the queen on a mating
mating virgin queens on a

2023-05-23 13:33 UTC, gregorgorjanc commented on vignettes/D_Crossing.Rmd
> +In this vignette, we first explain five technical ways of mating a virgin queens
Remove "technical"

2023-05-23 13:33 UTC, gregorgorjanc commented on vignettes/D_Crossing.Rmd
> +-   **create the cross plan internally**, either by sampling the mates randomly
change mates to the above

2023-05-23 13:33 UTC, gregorgorjanc requested changes
Minor points

would be good to get later feedback from @LStrachan and @JerBub once this is in the package - also Irene

2023-05-23 17:49 UTC, janaobsteter commented
@gregorgorjanc , I've addressed your comments and also solved some issues with using a sampling function in createCrossPlan().

2023-05-25 13:44 UTC, merged