Seeing the changes from my fork to HLab lab (remainder from the hackathon?)
HighlanderLab/SIMplyBee pull request #581
Opened 2024-07-17 08:09 UTC by janaobsteter

2024-07-17 08:17 UTC, janaobsteter reviewed
The factor in the "caste" was changed to "character", since the factor thing was making it slow and used memory. Also, I created generic functions to test whether we can improve the speed

2024-07-17 08:42 UTC, gregorgorjanc commented
@janaobsteter I am seeing this R CMD check (via GitHub action) failing with

```
Quitting from lines 618-622 [colony_strength] (F_Quantitative_Genetics.Rmd)
[308](https://github.com/HighlanderLab/SIMplyBee/actions/runs/9970676222/job/27550092259?pr=581#step:5:310)
Error: Error: processing vignette 'F_Quantitative_Genetics.Rmd' failed with diagnostics:
[309](https://github.com/HighlanderLab/SIMplyBee/actions/runs/9970676222/job/27550092259?pr=581#step:5:311)
no slot of name "queen" for this object of class "MultiColony"
[310](https://github.com/HighlanderLab/SIMplyBee/actions/runs/9970676222/job/27550092259?pr=581#step:5:312)
--- failed re-building ‘F_Quantitative_Genetics.Rmd’
[311](https://github.com/HighlanderLab/SIMplyBee/actions/runs/9970676222/job/27550092259?pr=581#step:5:313)
--- re-building ‘G_Sampling_functions.Rmd’ using rmarkdown
[312](https://github.com/HighlanderLab/SIMplyBee/actions/runs/9970676222/job/27550092259?pr=581#step:5:314)
--- finished re-building ‘G_Sampling_functions.Rmd’
[313](https://github.com/HighlanderLab/SIMplyBee/actions/runs/9970676222/job/27550092259?pr=581#step:5:315)
--- re-building ‘Z_FAQ.Rmd’ using rmarkdown
[314](https://github.com/HighlanderLab/SIMplyBee/actions/runs/9970676222/job/27550092259?pr=581#step:5:316)
--- finished re-building ‘Z_FAQ.Rmd’
[315](https://github.com/HighlanderLab/SIMplyBee/actions/runs/9970676222/job/27550092259?pr=581#step:5:317)
SUMMARY: processing the following file failed:
[316](https://github.com/HighlanderLab/SIMplyBee/actions/runs/9970676222/job/27550092259?pr=581#step:5:318)
  ‘F_Quantitative_Genetics.Rmd’
[317](https://github.com/HighlanderLab/SIMplyBee/actions/runs/9970676222/job/27550092259?pr=581#step:5:319)
Error: Error: Vignette re-building failed.
```

2024-07-17 08:44 UTC, gregorgorjanc commented on tests/testthat/test-L2_colony_functions.R
> +test_that("swarm1", {
Do we need a test for `buildUp1` too @janaobsteter ?

2024-07-17 08:45 UTC, gregorgorjanc reviewed
@janaobsteter looked over this - only one comment above and see the checks

2024-08-15 10:40 UTC, gregorgorjanc commented on src/isHeterozygous.o
This file should not be added to the repo

2024-08-15 10:42 UTC, gregorgorjanc commented on src/RcppExports.o
This file should not be in the repo

2024-08-15 10:42 UTC, gregorgorjanc commented on src/SIMplyBee.so
This file should not be in the repo

2024-08-15 10:43 UTC, gregorgorjanc commented on R/Functions_L0_auxilary.R
> -#' @examples
We likely need the `@examples` bit

2024-08-15 10:43 UTC, gregorgorjanc commented on R/Functions_L0_auxilary.R
> +  ret <- isGenoHeterozygous(geno)
I assume thins line is redundant

2024-08-15 10:43 UTC, gregorgorjanc requested changes
@janaobsteter see comments above

2024-08-20 14:54 UTC, gregorgorjanc commented on src/RcppExports.o
@janaobsteter this object file should be removed from git repo (add to `.gitignore` - see how Chris handles these)

2024-08-20 14:54 UTC, gregorgorjanc commented on src/SIMplyBee.so
@janaobsteter this object file should be removed from git repo (add to `.gitignore` - see how Chris handles these)

2024-08-20 14:55 UTC, gregorgorjanc commented on src/isHeterozygous.o
@janaobsteter this object file should be removed from git repo (add to `.gitignore` - see how Chris handles these)

2024-08-20 14:55 UTC, gregorgorjanc reviewed
@janaobsteter similar comments to last time;)

2024-08-23 12:23 UTC, gregorgorjanc commented on NEWS.md
@janaobsteter Add a note that we added isCsdHetero... to speed things a bit?

2024-08-23 12:24 UTC, gregorgorjanc commented on R/Functions_L0_auxilary.R
>      if(packageVersion("AlphaSimR") > package_version("1.5.3")){
@janaobsteter Best to just fix package version in DESCRIPTION and then we don't need this code duplication.

2024-08-23 12:26 UTC, gregorgorjanc commented on src/RcppExports.o
@janaobsteter remove this file from the repo - this is a compiled file

2024-08-23 12:26 UTC, gregorgorjanc commented on src/SIMplyBee.so
@janaobsteter remove this file from the repo - this is a compiled file

2024-08-23 12:27 UTC, gregorgorjanc requested changes
@janaobsteter looks good - needs minor tweaks and then we can merge

2024-08-28 08:02 UTC, janaobsteter commented
@gregorgorjanc , this is now the version accepted to CRAN. I've added all anchors to \links and removed the checks for AlphaSimR version since it now depends on the latest version with the correct handling of the misc slot.

Could you please merge this into HLab, then I can merge dev into main and I will also mark this as commit 0.4.0

2024-08-28 19:18 UTC, gregorgorjanc approved these changes
LGTM @janaobsteter! Thanks for doing all this edits for the help page linking! That must have been annoying.

2024-08-28 19:19 UTC, merged